server:
  port: 8001
spring:
  datasource:
    url: ${POSTGRES_DATABASE_URL:jdbc:postgresql://localhost:5432/customers}
    username: ${POSTGRES_DATABASE_USERNAME:postgres}
    password: ${POSTGRES_DATABASE_PASSWORD:1234}
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: 'none'
    #    properties:
    #      hibernate:
    #        temp:
    #          use_jdbc_metadata_defaults: false
    #        jdbc:
    #          lob:
    #            non_contextual_creation: true
    generate-ddl: true
springdoc:
  api-docs:
    path: '/api-docs'