server:
  port: 8001
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/psycho-service}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: 'none'
    #    properties:
    #      hibernate:
    #        temp:
    #          use_jdbc_metadata_defaults: false
    #        jdbc:
    #          lob:
    #            non_contextual_creation: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    path: '/api-docs'
amazonProperties:
  endpointUrl: https://s3.eu-central-1.amazonaws.com
  accessKey: AKIAYM5J67CXUEBIOJM7
  secretKey: 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
  bucketName: thesis-belstu
