create table admin (id VARCHAR(255) not null, primary key (id));
create table authorities (id VARCHAR(255) not null, name varchar(255), primary key (id));
create table chats (id VARCHAR(255) not null, chat_status varchar(50) not null, chat_type varchar(50) not null, client_id VARCHAR(255), psychologist_id VARCHAR(255), primary key (id));
create table client (avatar_url varchar(100), birthday_date date not null, id VARCHAR(255) not null, primary key (id));
create table comments (id VARCHAR(255) not null, creation_date timestamp not null, text TEXT not null, post_id VARCHAR(255), user_id VARCHAR(255), primary key (id));
create table event (id VARCHAR(255) not null, date timestamp not null, feedback varchar(255), is_confirmed boolean not null, is_ended boolean not null, is_repeated boolean, reason_for_visit varchar(255), room_id varchar(255), client_id VARCHAR(255), prescription_id VARCHAR(255), note_id VARCHAR(255), psychologist_id VARCHAR(255), primary key (id));
create table feedback (id VARCHAR(255) not null, text varchar(255) not null, client_id VARCHAR(255), primary key (id));
create table files_attribute (id VARCHAR(255) not null, type varchar(50) not null, object_id varchar(255), url varchar(255), primary key (id));
create table messages (id VARCHAR(255) not null, creation_date timestamp not null, status varchar(50) not null, text TEXT not null, chat_id VARCHAR(255), recipient_id VARCHAR(255), sender_id VARCHAR(255), primary key (id));
create table notes (id VARCHAR(255) not null, special_notes varchar(255), symptoms varchar(255), primary key (id));
create table posts (id VARCHAR(255) not null, post_date date not null, text TEXT not null, title varchar(100) not null, psychologist_id VARCHAR(255), primary key (id));
create table prescription (id VARCHAR(255) not null, recommendations varchar(255), primary key (id));
create table psycho_workday (id VARCHAR(255) not null, date date not null, end_date_time timestamp not null, start_date_time timestamp not null, psychologist_id VARCHAR(255), primary key (id));
create table psychologist (avatar_url varchar(100), education varchar(100), mobile varchar(20), is_verified boolean not null, verified_date date, id VARCHAR(255) not null, primary key (id));
create table psychologist_client (psychologist_id VARCHAR(255) not null, client_id VARCHAR(255) not null, primary key (psychologist_id, client_id));
create table psychologist_tag (psychologist_id VARCHAR(255) not null, tag_id VARCHAR(255) not null, primary key (psychologist_id, tag_id));
create table role_authority (authority_id VARCHAR(255) not null, role_id VARCHAR(255) not null, primary key (authority_id, role_id));
create table roles (id VARCHAR(255) not null, user_role varchar(50) not null, primary key (id));
create table support (id VARCHAR(255) not null, created_admin_id VARCHAR(255), primary key (id));
create table tag (id VARCHAR(255) not null, name varchar(50) not null, primary key (id));
create table user_role (user_id VARCHAR(255) not null, role_id VARCHAR(255) not null, primary key (user_id, role_id));
create table users (id VARCHAR(255) not null, is_deactivated boolean not null, deactivated_date date, email varchar(100) not null, first_name varchar(100) not null, image_url varchar(255), last_name varchar(100) not null, middle_name varchar(100) not null, password varchar(255) not null, register_date date not null, primary key (id));
alter table if exists roles add constraint UK_of3ju3rqw7vy773g0hwrkx02s unique (user_role);
alter table if exists tag add constraint UK_1wdpsed5kna2y38hnbgrnhi5b unique (name);
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists admin add constraint FKqer4e53tfnl17s22ior7fcsv8 foreign key (id) references users;
alter table if exists chats add constraint FKe1cmw7vtpk5y09502dlfyvky7 foreign key (client_id) references client;
alter table if exists chats add constraint FKby2evasx3ilj2mrthrmdfq0m8 foreign key (psychologist_id) references psychologist;
alter table if exists client add constraint FK70dfjxvqnmgixqht3vea50voj foreign key (id) references users;
alter table if exists comments add constraint FKh4c7lvsc298whoyd4w9ta25cr foreign key (post_id) references posts;
alter table if exists comments add constraint FK8omq0tc18jd43bu5tjh6jvraq foreign key (user_id) references users;
alter table if exists event add constraint FKtpp6e5l87vdkxia1nfxv2r3il foreign key (client_id) references client;
alter table if exists event add constraint FKlr3tbg7bjawoxxexdwkt4vncl foreign key (prescription_id) references prescription;
alter table if exists event add constraint FK9p70huh3f4i80ybr2tfrtdagr foreign key (note_id) references notes;
alter table if exists event add constraint FKme49g970lgqj5xvv1j73x1dxw foreign key (psychologist_id) references psychologist;
alter table if exists feedback add constraint FK9rh73oafv80ggwri04l9223bi foreign key (client_id) references client;
alter table if exists messages add constraint FK64w44ngcpqp99ptcb9werdfmb foreign key (chat_id) references chats;
alter table if exists messages add constraint FKhdkwfnspwb3s60j27vpg0rpg6 foreign key (recipient_id) references users;
alter table if exists messages add constraint FK4ui4nnwntodh6wjvck53dbk9m foreign key (sender_id) references users;
alter table if exists posts add constraint FKmoarca64dxcksxwsxtjbfncko foreign key (psychologist_id) references psychologist;
alter table if exists psycho_workday add constraint FK15c0rw3opbq1ugw2wsr0o9fx0 foreign key (psychologist_id) references psychologist;
alter table if exists psychologist add constraint FK9bmxvh4w2ifvcgv8936bk6uuk foreign key (id) references users;
alter table if exists psychologist_client add constraint FK7wfnr5q2nhgmgc02yw9fcgfm1 foreign key (client_id) references client;
alter table if exists psychologist_client add constraint FKmsyx8lhj6u8s9wnfs289aculy foreign key (psychologist_id) references psychologist;
alter table if exists psychologist_tag add constraint FKh3h18x6dlk2b5nj4beod4evqh foreign key (tag_id) references tag;
alter table if exists psychologist_tag add constraint FK81gerl4cf4modhk6cj8drgy3q foreign key (psychologist_id) references psychologist;
alter table if exists role_authority add constraint FK78r7yh1uqg30liv2n75ay99j foreign key (role_id) references roles;
alter table if exists role_authority add constraint FKpduid6tx7e38l03s86446514r foreign key (authority_id) references authorities;
alter table if exists support add constraint FKar2um7wvl26dsafpajgrpaklp foreign key (created_admin_id) references admin;
alter table if exists support add constraint FKn4ajxyra4ermnjwpvfv9miikm foreign key (id) references users;
alter table if exists user_role add constraint FKt7e7djp752sqn6w22i6ocqy6q foreign key (role_id) references roles;
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users;
